### ISSUE TITLE
Can latest `derfinder` reproduce original (2013) analysis?

### ISSUE THREAD

**Issue by brianhigh** [lcolladotor/derfinder#30]
Can the analysis in the paper [Differential expression analysis of RNA-seq data at single-base resolution](http://biostatistics.oxfordjournals.org/content/early/2014/01/06/biostatistics.kxt053.full) be reproduced using the latest version of `derfinder`? I ask because I am having a [difficult time](https://github.com/alyssafrazee/derfinder/issues) doing so using the "beta" version of the [code](https://github.com/alyssafrazee/derfinder) and [analysis_code.R](https://github.com/alyssafrazee/derfinder/blob/master/analysis_code.R). Thanks for any help you can provide.

**Comment by lcolladotor** [comment]
The software from the 2013 paper is different from this one as they use different statistical models. If you want to reproduce those results use https://github.com/alyssafrazee/derfinder

You can alternatively use this `derfinder` implementation to compare the results. Aka, replicate but not reproduce.
