### ISSUE TITLE
create a UCSC Track Hub from derfinder results

### ISSUE THREAD

**Issue by andrewejaffe** [lcolladotor/derfinder#31]
it would eventually be nice to have code that takes adjusted coverage, derfinder results, and the genome-wide F-statistic used to find the DERs, and automatically create a UCSC Track Hub. Other inputs would maybe need to be genome build (although it could perhaps be inferred from the genome info on the DERs)

The general structure involves two files called hub.txt and genomes.txt then a folder named as the genome build, which contains BigWigs and bigBeds. These are from my track hub from our nature neuroscience paper: https://s3.amazonaws.com/DLPFC_n36/humanDLPFC/hub.txt . I don't think it would be that hard to at least make a skeleton Track Hub using a simple wrapper.

**Example hub.txt**

hub humanDLPFC 
shortLabel LIBD Human DLPFC Development
longLabel RNAseq data across human brain development by age group from LIBD
genomesFile genomes.txt
email andrew.jaffe@libd.org
descriptionUrl http://www.libd.org

**Example genomes.txt**
genome hg19
trackDb hg19/trackDb.txt

**Then there is a folder called hg19/ that contains trackDb.txt, example:**
track DERs
bigDataUrl DERs.bigBed
shortLabel DERs
longLabel Differentially expressed regions (DERs) across brain development
type bigBed 5 .
priority 1
visibility dense

track sixGroup_F
bigDataUrl sixGroup_Fstat_DLPFC_LIBD.bw
shortLabel sixGroup_F
longLabel F-statistic for 36 samples across 6 age groups
type bigWig
priority 2
visibility full
maxHeightPixels 100:32:8
yLineOnOff on
yLineMark 20.51
viewLimitsMax 0:200
viewLimits 0:50
autoscale on

track sixGroupMulti
shortLabel sixGroupDLPFC
longLabel Comparison in human DLPFC across six age groups 
container multiWig
aggregate none
showSubtrackColorOnUi on
type bigWig
priority 3
maxHeightPixels 100:32:8
visibility full
yLineOnOff on
yLineMark 5

```
    track FetalOverlay
    parent sixGroupMulti
    shortLabel Fetal DLPFC
    longLabel Normalized RNAseq coverage (Reads/80M) averaged across 6 fetal brains 
    color 27,158,119
    type bigWig
    priority 2
    bigDataUrl Fetal_DLPFC_LIBD_meanExp.bw

    track InfantOverlay
    shortLabel Infant DLPFC
    longLabel Normalized RNAseq coverage (Reads/80M) averaged across 6 infant brains 
    parent sixGroupMulti
    color 217,95,2
    type bigWig 
    priority 3
    bigDataUrl Infant_DLPFC_LIBD_meanExp.bw

    track ChildOverlay
    parent sixGroupMulti
    shortLabel Child DLPFC
    longLabel Normalized RNAseq coverage (Reads/80M) averaged across 6 child brains 
    color 117,112,179
    type bigWig 
    priority 4
    bigDataUrl Child_DLPFC_LIBD_meanExp.bw

    track TeenOverlay
    parent sixGroupMulti
    shortLabel Teen DLPFC
    longLabel Normalized RNAseq coverage (Reads/80M) averaged across 6 teen brains 
    color 231,41,138
    type bigWig
    priority 5
    bigDataUrl Teen_DLPFC_LIBD_meanExp.bw

    track AdultOverlay
    parent sixGroupMulti
    shortLabel Adult DLPFC 
    longLabel Normalized RNAseq coverage (Reads/80M) averaged across 6 adult brains 
    color 102,166,30
    type bigWig
    priority 6
    bigDataUrl Adult_DLPFC_LIBD_meanExp.bw

    track 50plusOverlay
    parent sixGroupMulti
    shortLabel 50plus DLPFC
    longLabel Normalized RNAseq coverage (Reads/80M) averaged across 6 elderly brains 
    color 230,171,2
    type bigWig
    bigDataUrl 50plus_DLPFC_LIBD_meanExp.bw
    priority 7
```

**Comment by lcolladotor** [comment]
http://www.bioconductor.org/packages/release/bioc/html/GenomicInteractions.html could be related to this

**Comment by lcolladotor** [comment]
@andrewejaffe Doesn't look like this is a much needed feature. Is it ok to close the issue?

**Comment by andrewejaffe** [comment]
sure.
-a
